/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    RunArea: typeof import('./src/components/RunArea.vue')['default']
    TimeNow: typeof import('./src/components/TimeNow.vue')['default']
    Toast: typeof import('./src/components/Toast.vue')['default']
  }
}
